sudo: false
language: node_js
node_js:
  - "14.15"
branches:
  only:
    - main
    - /^add-.*$/
cache:
  directories:
    - node_modules
env:
  - SKIP_PREFLIGHT_CHECK=true
before_install:
  # TODO, must configure AWS
  # - yarn build && yarn deploy
  - yarn upgrade
install:
  - yarn install
script:
  - yarn test src/tests/Divider
